modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"

[[mods]]
modId = "datmoddingapi"
version = "${mod_version}"
displayName = "Dat Modding API"
authors = "jtljac"
displayTest="IGNORE_SERVER_VERSION"

description = '''
A modding library for DatDeveloper
'''

[[dependencies.datmoddingapi]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.datmoddingapi]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.datmoddingapi]]
modId = "spongeforge"
mandatory = false
versionRange = "[8.0.0,)"
ordering = "NONE"
side = "SERVER"