modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Dat-Developer-Mods/datmoddingapi/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL = "datdeveloper.com"
logoFile = "datmoddingapi.png"
#credits="Thanks for this example mod goes to Java"
authors = "${mod_authors}"
displayTest = "IGNORE_SERVER_VERSION"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "spongeforge"
mandatory = false
versionRange = "[8.0.0,)"
ordering = "NONE"
side = "SERVER"